### ISSUE TITLE
feat: preserve zoom level onClick

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-pageview-map#34]
## Summary

After zooming into the map (utilizing touchpad), when you select a point, it centers you on that point but zooms back out.

## Desired Behavior

Preserve zoom-level so you don't feel like you're being jostled/bounced around.

## Possible Solution

Add a listener to the map for `onZoomLevel` (or similar) and store the zoom level in local state.

**Comment by dulcineapena1** [comment]
@devfreddy It also do this on desktop. I have done some changes, I will do my pull request and will wait for any comments.

**Comment by tangollama** [comment]
Thanks for this work @dulcineapena1. Closing this issue now.
